# Use latest node version 10.x
FROM node:10.15.0-slim

# RUN npm install -g pm2
# create app directory in container
RUN mkdir -p /app

# set /app directory as default working directory
WORKDIR /app

# copy all file from current dir to /app in container
COPY . /app/

# expose port 5000
EXPOSE 5000

# cmd to start service
CMD [ "yarn", "startup" ]
